version: 0.0
os: linux

permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /home/ec2-user/scripts
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /home/ec2-user/scripts/*
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
